[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"


[dependencies]
actix-web = "4"
actix-rt = "2.9.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1", features = ["derive"] }
config = "0.13.3"
uuid = { version = "1.4.1", features = ["v4"] }
chrono = "0.4.26"
env_logger = "0.10.0"
tracing = { version = "0.1", features = ["log"] }
log = "0.4.20"
tracing-subscriber = { version = "0.2.12", features = [
    "registry",
    "env-filter",
] }
tracing-bunyan-formatter = "0.2"
tracing-log = "0.1.3"
tracing-actix-web = "0.7.6"
serde-aux = "4.2.0"
unicode-segmentation = "1.10.1"
validator = "0.16.1"
rand = { version = "0.8.5", features = ["std_rng"] }
thiserror = "1.0.48"
anyhow = "1.0.75"
base64 = "0.21.4"
sha3 = "0.10.8"
argon2 = { version = "0.5.2", features = ["std"] }


[dependencies.sqlx]
version = "0.7.1"
default-features = false
features = [
    # "runtime-actix-rustls",
    "runtime-tokio",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    # "offline",
]

[dev-dependencies]
claim = "0.5.0"
once_cell = "1.18.0"
fake = "2.8.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
wiremock = "0.5.19"
serde_json = "1.0"
linkify = "0.10.0"
